// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/18/2026, 11:12:42 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/jeffr/Documents/GitHub/DepthLab/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jeffr/Documents/GitHub/DepthLab/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jeffr/Documents/GitHub/DepthLab/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jeffr/Documents/GitHub/DepthLab/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jeffr/Documents/GitHub/DepthLab/plugins/**/*.{js,ts,mjs}","C:/Users/jeffr/Documents/GitHub/DepthLab/composables/**/*.{js,ts,mjs}","C:/Users/jeffr/Documents/GitHub/DepthLab/utils/**/*.{js,ts,mjs}","C:/Users/jeffr/Documents/GitHub/DepthLab/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jeffr/Documents/GitHub/DepthLab/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jeffr/Documents/GitHub/DepthLab/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jeffr/Documents/GitHub/DepthLab/app.config.{js,ts,mjs}","C:/Users/jeffr/Documents/GitHub/DepthLab/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;